eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: app-account-service
  data:
    mongodb:
      database: dbTest
      host: localhost
      port: 27017

server:
  port: 9092